CREATE TABLE SubscriptionPlans (
  PlanID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  Name NVARCHAR(100) NOT NULL,
  PriceMonthly DECIMAL(10,2) NOT NULL DEFAULT 0,
  MaxUsers INT NULL,
  MaxPatients INT NULL,
  Features NVARCHAR(MAX) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_SubscriptionPlans_Name UNIQUE (Name),
  CONSTRAINT CK_SubscriptionPlans_Features_Json CHECK (Features IS NULL OR ISJSON(Features) = 1)
);
