CREATE TABLE Users (
  UserID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NULL,
  Username NVARCHAR(100) NOT NULL,
  PasswordHash NVARCHAR(255) NOT NULL,
  Role NVARCHAR(20) NOT NULL,
  FullName NVARCHAR(255) NOT NULL,
  Email NVARCHAR(255) NULL,
  Phone NVARCHAR(50) NULL,
  Status NVARCHAR(20) NOT NULL DEFAULT 'Active',
  MustChangePassword BIT NOT NULL DEFAULT 0,
  RefreshTokenHash NVARCHAR(255) NULL,
  LastLoginAt DATETIME2 NULL,
  FailedLoginAttempts INT NOT NULL DEFAULT 0,
  LockedUntil DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CreatedBy UNIQUEIDENTIFIER NULL,
  UpdatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedBy UNIQUEIDENTIFIER NULL,
  CONSTRAINT UQ_Users_Username UNIQUE (Username),
  CONSTRAINT CK_Users_Role CHECK (Role IN ('SUPER_ADMIN','CLINIC_ADMIN','DOCTOR','RECEPTIONIST','NURSE')),
  CONSTRAINT CK_Users_Status CHECK (Status IN ('Active','Inactive','Locked')),
  CONSTRAINT CK_Users_SuperAdminNoClinic CHECK (
    (Role = 'SUPER_ADMIN' AND ClinicID IS NULL) OR (Role <> 'SUPER_ADMIN' AND ClinicID IS NOT NULL)
  ),
  CONSTRAINT FK_Users_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID)
);
GO

CREATE INDEX IX_Users_ClinicID ON Users(ClinicID);
