CREATE TABLE Doctors (
  DoctorID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NOT NULL,
  UserID UNIQUEIDENTIFIER NOT NULL,
  DoctorName NVARCHAR(255) NOT NULL,
  Specialization NVARCHAR(255) NULL,
  Qualifications NVARCHAR(500) NULL,
  LicenseNo NVARCHAR(100) NULL,
  ConsultationFee DECIMAL(10,2) NOT NULL DEFAULT 0,
  FollowUpFee DECIMAL(10,2) NOT NULL DEFAULT 0,
  RoomNo NVARCHAR(50) NULL,
  SignatureUrl NVARCHAR(500) NULL,
  Status NVARCHAR(20) NOT NULL DEFAULT 'Active',
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT CK_Doctors_Status CHECK (Status IN ('Active','Inactive')),
  CONSTRAINT UQ_Doctors_UserID UNIQUE (UserID),
  CONSTRAINT FK_Doctors_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID),
  CONSTRAINT FK_Doctors_User FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
GO

CREATE INDEX IX_Doctors_ClinicID ON Doctors(ClinicID);
