CREATE TABLE DoctorLeaves (
  LeaveID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NOT NULL,
  DoctorID UNIQUEIDENTIFIER NOT NULL,
  LeaveDate DATE NOT NULL,
  Reason NVARCHAR(255) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_DoctorLeaves_Doctor_Date UNIQUE (DoctorID, LeaveDate),
  CONSTRAINT FK_DoctorLeaves_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID),
  CONSTRAINT FK_DoctorLeaves_Doctor FOREIGN KEY (DoctorID) REFERENCES Doctors(DoctorID)
);
