CREATE TABLE Vitals (
  VitalID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NOT NULL,
  PatientID UNIQUEIDENTIFIER NOT NULL,
  AppointmentID UNIQUEIDENTIFIER NULL,
  RecordedByUserID UNIQUEIDENTIFIER NOT NULL,
  BPSystolic INT NULL,
  BPDiastolic INT NULL,
  PulseRate INT NULL,
  Temperature DECIMAL(4,1) NULL,
  Weight DECIMAL(5,2) NULL,
  Height DECIMAL(5,2) NULL,
  BMI DECIMAL(5,2) NULL,
  SpO2 INT NULL,
  BloodSugar DECIMAL(6,2) NULL,
  RecordedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Vitals_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID),
  CONSTRAINT FK_Vitals_Patient FOREIGN KEY (PatientID) REFERENCES Patients(PatientID),
  CONSTRAINT FK_Vitals_Appointment FOREIGN KEY (AppointmentID) REFERENCES Appointments(AppointmentID),
  CONSTRAINT FK_Vitals_RecordedBy FOREIGN KEY (RecordedByUserID) REFERENCES Users(UserID)
);
GO

CREATE INDEX IX_Vitals_Clinic_Patient ON Vitals(ClinicID, PatientID);
