CREATE TABLE Medicines (
  MedicineID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NOT NULL,
  Name NVARCHAR(255) NOT NULL,
  GenericName NVARCHAR(255) NULL,
  DefaultDosage NVARCHAR(100) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT UQ_Medicines_Clinic_Name UNIQUE (ClinicID, Name),
  CONSTRAINT FK_Medicines_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID)
);
