CREATE TABLE LabTests (
  LabTestID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NOT NULL,
  Name NVARCHAR(255) NOT NULL,
  Category NVARCHAR(100) NULL,
  Price DECIMAL(10,2) NOT NULL DEFAULT 0,
  IsActive BIT NOT NULL DEFAULT 1,
  CONSTRAINT UQ_LabTests_Clinic_Name UNIQUE (ClinicID, Name),
  CONSTRAINT FK_LabTests_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID)
);
