CREATE TABLE InvoiceItems (
  InvoiceItemID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  InvoiceID UNIQUEIDENTIFIER NOT NULL,
  Description NVARCHAR(255) NOT NULL,
  Quantity INT NOT NULL DEFAULT 1,
  UnitPrice DECIMAL(12,2) NOT NULL DEFAULT 0,
  Amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT FK_InvoiceItems_Invoice FOREIGN KEY (InvoiceID) REFERENCES Invoices(InvoiceID)
);
GO

CREATE INDEX IX_InvoiceItems_InvoiceID ON InvoiceItems(InvoiceID);
