CREATE TABLE AuditLogs (
  LogID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NULL,
  UserID UNIQUEIDENTIFIER NULL,
  Action NVARCHAR(50) NOT NULL,
  Entity NVARCHAR(100) NOT NULL,
  EntityID NVARCHAR(100) NULL,
  OldValues NVARCHAR(MAX) NULL,
  NewValues NVARCHAR(MAX) NULL,
  IPAddress NVARCHAR(64) NULL,
  Timestamp DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT CK_AuditLogs_OldValues_Json CHECK (OldValues IS NULL OR ISJSON(OldValues) = 1),
  CONSTRAINT CK_AuditLogs_NewValues_Json CHECK (NewValues IS NULL OR ISJSON(NewValues) = 1),
  CONSTRAINT FK_AuditLogs_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID),
  CONSTRAINT FK_AuditLogs_User FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
GO

CREATE INDEX IX_AuditLogs_Clinic_Timestamp ON AuditLogs(ClinicID, Timestamp);
CREATE INDEX IX_AuditLogs_UserID ON AuditLogs(UserID);
