CREATE TABLE Notifications (
  NotificationID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NOT NULL,
  UserID UNIQUEIDENTIFIER NOT NULL,
  Type NVARCHAR(50) NOT NULL,
  Title NVARCHAR(255) NOT NULL,
  Message NVARCHAR(1000) NULL,
  IsRead BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Notifications_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID),
  CONSTRAINT FK_Notifications_User FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
GO

CREATE INDEX IX_Notifications_User_IsRead ON Notifications(UserID, IsRead);
