CREATE TABLE Documents (
  DocumentID UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
  ClinicID UNIQUEIDENTIFIER NOT NULL,
  PatientID UNIQUEIDENTIFIER NOT NULL,
  UploadedByUserID UNIQUEIDENTIFIER NOT NULL,
  FileName NVARCHAR(255) NOT NULL,
  FilePath NVARCHAR(500) NOT NULL,
  FileType NVARCHAR(50) NULL,
  FileSizeBytes BIGINT NULL,
  Description NVARCHAR(500) NULL,
  UploadedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT FK_Documents_Clinic FOREIGN KEY (ClinicID) REFERENCES Clinics(ClinicID),
  CONSTRAINT FK_Documents_Patient FOREIGN KEY (PatientID) REFERENCES Patients(PatientID),
  CONSTRAINT FK_Documents_UploadedBy FOREIGN KEY (UploadedByUserID) REFERENCES Users(UserID)
);
GO

CREATE INDEX IX_Documents_Clinic_Patient ON Documents(ClinicID, PatientID);
